#!/usr/bin/env python3

import argparse

parser = argparse.ArgumentParser(
    prog="mc python",
    description="Demonstrate a python based sub command",
    epilog="Text at the bottom of help",
)

parser.add_argument("filename")
parser.add_argument("-c", "--count")

args = parser.parse_args()

print(args)
